
 /**
  * This template file was generated by dynaTrace client.
  * The dynaTrace community portal can be found here: http://community.compuwareapm.com/
  * For information how to publish a plugin please visit http://community.compuwareapm.com/plugins/contribute/
  **/ 

package com.accesshq.weather;

import com.dynatrace.diagnostics.pdk.*;

import java.net.URL;
import java.util.Collection;
import java.util.logging.Logger;
import org.apache.commons.io.IOUtils;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

public class monitor implements Monitor {

	private static final Logger log = Logger.getLogger(monitor.class.getName());


	/**
	 * Initializes the Plugin. This method is called in the following cases:
	 * <ul>
	 * <li>before <tt>execute</tt> is called the first time for this
	 * scheduled Plugin</li>
	 * <li>before the next <tt>execute</tt> if <tt>teardown</tt> was called
	 * after the last execution</li>
	 * </ul>
	 * <p>
	 * If the returned status is <tt>null</tt> or the status code is a
	 * non-success code then {@link Plugin#teardown() teardown()} will be called
	 * next.
	 * <p>
	 * Resources like sockets or files can be opened in this method.
	 * @param env
	 *            the configured <tt>MonitorEnvironment</tt> for this Plugin;
	 *            contains subscribed measures, but <b>measurements will be
	 *            discarded</b>
	 * @see Plugin#teardown()
	 * @return a <tt>Status</tt> object that describes the result of the
	 *         method call
	 */
	@Override
	public Status setup(MonitorEnvironment env) throws Exception {
		// TODO
		return new Status(Status.StatusCode.Success);
	}

	/**
	 * Executes the Monitor Plugin to retrieve subscribed measures and store
	 * measurements.
	 *
	 * <p>
	 * This method is called at the scheduled intervals. If the Plugin execution
	 * takes longer than the schedule interval, subsequent calls to
	 * {@link #execute(MonitorEnvironment)} will be skipped until this method
	 * returns. After the execution duration exceeds the schedule timeout,
	 * {@link TaskEnvironment#isStopped()} will return <tt>true</tt>. In this
	 * case execution should be stopped as soon as possible. If the Plugin
	 * ignores {@link TaskEnvironment#isStopped()} or fails to stop execution in
	 * a reasonable timeframe, the execution thread will be stopped ungracefully
	 * which might lead to resource leaks!
	 *
	 * @param env
	 *            a <tt>MonitorEnvironment</tt> object that contains the
	 *            Plugin configuration and subscribed measures. These
	*            <tt>MonitorMeasure</tt>s can be used to store measurements.
	 * @return a <tt>Status</tt> object that describes the result of the
	 *         method call
	 */
	@Override
	public Status execute(MonitorEnvironment env) throws Exception {
 
		JSONParser parser = new JSONParser();
		
		String apiKey = env.getConfigString("OpenWeatherMapKey");
		String city = env.getConfigString("City");
		String celFah = env.getConfigString("CelFah");
		String unit = "imperial";
		if (celFah.toUpperCase().trim().startsWith("C")) {
			unit = "metric";
		}
	
		log.info("celFah: " + celFah + ", unit: " + unit);
		log.info("url: " + "http://api.openweathermap.org/data/2.5/weather?q=" + city + "&units=" + unit + "&appid=" + apiKey);
		Object obj = parser.parse(IOUtils.toString(new URL("http://api.openweathermap.org/data/2.5/weather?q=" + city + "&units=" + unit + "&appid=" + apiKey)));
		JSONObject jsonObject = (JSONObject) obj;
		Status resultStat = new Status(Status.StatusCode.Success);
		
		Collection<MonitorMeasure> monitorMeasures = env.getMonitorMeasures("group1", "temperature");
		if (monitorMeasures != null) {
			for (MonitorMeasure subscribedMonitorMeasure : monitorMeasures) {
	
				//this will book to the monitor measure
				JSONObject main = (JSONObject) jsonObject.get("main");
				Double temperature = (Double) main.get("temp");
				subscribedMonitorMeasure.setValue(temperature);
			}
	
			monitorMeasures = env.getMonitorMeasures("group1", "pollutionIndex");
			for (MonitorMeasure subscribedMonitorMeasure : monitorMeasures) {
				subscribedMonitorMeasure.setValue(24);
			}
	
			monitorMeasures = env.getMonitorMeasures("group1", "uvIndex");
			for (MonitorMeasure subscribedMonitorMeasure : monitorMeasures) {
				subscribedMonitorMeasure.setValue(32);
			}
		}
		else {
			resultStat.setMessage("Monitor Measures not found");
		}
		//for this subscribed measure we want to create a dynamic measure
		//MonitorMeasure dynamicMeasure = env.createDynamicMeasure(null, "group1", "pollutionIndex");
		//dynamicMeasure.setValue(24);

		return resultStat;
	}

	/**
	 * Shuts the Plugin down and frees resources. This method is called in the
	 * following cases:
	 * <ul>
	 * <li>the <tt>setup</tt> method failed</li>
	 * <li>the Plugin configuration has changed</li>
	 * <li>the execution duration of the Plugin exceeded the schedule timeout</li>
	 * <li>the schedule associated with this Plugin was removed</li>
	 * </ul>
	 *
	 * <p>
	 * The Plugin methods <tt>setup</tt>, <tt>execute</tt> and
	 * <tt>teardown</tt> are called on different threads, but they are called
	 * sequentially. This means that the execution of these methods does not
	 * overlap, they are executed one after the other.
	 *
	 * <p>
	 * Examples:
	 * <ul>
	 * <li><tt>setup</tt> (failed) -&gt; <tt>teardown</tt></li>
	 * <li><tt>execute</tt> starts, configuration changes, <tt>execute</tt>
	 * ends -&gt; <tt>teardown</tt><br>
	 * on next schedule interval: <tt>setup</tt> -&gt; <tt>execute</tt> ...</li>
	 * <li><tt>execute</tt> starts, execution duration timeout,
	 * <tt>execute</tt> stops -&gt; <tt>teardown</tt></li>
	 * <li><tt>execute</tt> starts, <tt>execute</tt> ends, schedule is
	 * removed -&gt; <tt>teardown</tt></li>
	 * </ul>
	 * Failed means that either an unhandled exception is thrown or the status
	 * returned by the method contains a non-success code.
	 *
	 *
	 * <p>
	 * All by the Plugin allocated resources should be freed in this method.
	 * Examples are opened sockets or files.
	 *
	 * @see Monitor#setup(MonitorEnvironment)
	 */	@Override
	public void teardown(MonitorEnvironment env) throws Exception {
		// TODO
	}
}
